---
title: "Men/Women"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1) Data
```{r}
#men
thesis.df_social_m <- thesis.df_social %>% filter(Демографія == 'Чоловік')

#women
thesis.df_social_w <- thesis.df_social %>% filter(Демографія == 'Жінка')
```


2) Mallet M
```{r}
topic.model_social_m <- MalletLDA(num.topics=35) # number of topics
topic.model_social_m$setRandomSeed(12345L)

mallet.instances_social_m <- mallet.import(text.array=as.character(thesis.df_social_m$cleaned_post),
                                  stoplist="stopwords.txt") 

topic.model_social_m$loadDocuments(mallet.instances_social_m) 

topic.model_social_m$setAlphaOptimization(20, 50) # optimizing hyperparameters

vocabulary_social_m <- topic.model_social_m$getVocabulary() # corpus dictionary
word.freqs_social_m <- mallet.word.freqs(topic.model_social_m) # frequency table
```


```{r}
set.seed(123)
topic.model_social_m$train(500)
topic.model_social_m$maximize(10)
doc.topics_social_m <- mallet.doc.topics(topic.model_social_m, smoothed=TRUE, normalized=TRUE)
topic.words_social_m <- mallet.topic.words(topic.model_social_m, smoothed=TRUE, normalized=TRUE)
topic.labels_social_m <- mallet.topic.labels(topic.model_social_m, topic.words_social, 10)

top.docs <- function(doc.topics_social_m, topic.model_social_m, docs, top.n=49) {
    head(docs[order(-doc.topics_social_m[,topic])], top.n)
}

#r9_m = as.data.frame(top.docs(doc.topics_social_m2, 9, thesis.df_social_m2$Дайджест.текста))
 
lapply(1:nrow(topic.words_social_m), function(k) {
    top <- mallet.top.words(topic.model_social_m, topic.words_social_m[k,], 10) %>% select("term")
    cat(paste(k, top, "\n")) 
})
```

```{r}
#m3  = as.data.frame(top.docs(doc.topics_social_m, 3, thesis.df_social_m2$Дайджест.текста))
#r3.2 <- as.data.frame(r3[c(3, 11, 15), ])
#r9.2 <- as.data.frame(r9_m[c(2, 5, 7, 10, 12), ])
#r22.2 <-as.data.frame(r22[c(1, 10, 11, 12, 13), ])
#r27.2 <- as.data.frame(r27[c(1, 9, 13, 14), ])


#write.xlsx(sm27, 'D://mallet/s27.xlsx')
```

```{r}
topic_labels_social_m <- mallet.topic.labels(topic.model_social_m, num.top.words = 2)
topic_clusters_social_m <- mallet.topic.hclust(doc.topics_social_m, topic.words_social_m, balance = 0.5)
plot(topic_clusters_social_m, labels=topic_labels2, xlab = "", )
```

Visualization M
```{r}
m_social_m <- mallet_model(doc_topics = doc.topics_social_m, doc_ids = thesis.df_social_m$id, vocab = 
vocabulary_social_m, topic_words = topic.words_social_m, model = topic.model_social_m)
meta_social_m <- data.frame(id = thesis.df_social_m$id, pubdate = as.Date(thesis.df_social_m$Дата, "%d.%m.%Y"))
metadata(m_social_m) <- meta_social_m
series_social_m <- a(m_social_m, 'days')
theme_update(strip.text=element_text(size=7), 
axis.text=element_text(size=7))

a(m_social_m) %>%
plot_series(labels=topic_labels(m_social_m, 2))

```

```{r}

cols = rainbow(35, s=.6, v=.9)[sample(1:35,35)]

plot_social_m = ggplot(series_social_m, aes(x=pubdate, y=weight, fill=as.character(topic)))
plot_social_m + 
  geom_area() +
  geom_area(alpha=0.6 , size=.2, colour="white") +
  theme_bw() + scale_fill_manual(values=cols)
  
#save.mallet.state(topic.model = topic.model_social_m, state.file = "D://mallet/social_m2_mallet_state.gz")
#mallet.topic.model.write(topic.model = topic.model_social_m, 'D://mallet/social_m2_mal.model')
```


3) Mallet W
```{r}
topic.model_social_w <- MalletLDA(num.topics=35) # number of topics
topic.model_social_w$setRandomSeed(12345L)

mallet.instances_social_w <- mallet.import(text.array=as.character(thesis.df_social_w$cleaned_post),
                                  stoplist="stopwords.txt") 

topic.model_social_w$loadDocuments(mallet.instances_social_w) 

topic.model_social_w$setAlphaOptimization(20, 50) # optimizing hyperparameters

vocabulary_social_w <- topic.model_social_w$getVocabulary() # corpus dictionary
word.freqs_social_w <- mallet.word.freqs(topic.model_social_w) # frequency table
```

```{r}

set.seed(123)
topic.model_social_w$train(500)
topic.model_social_w$maximize(10)
doc.topics_social_w <- mallet.doc.topics(topic.model_social_w, smoothed=TRUE, normalized=TRUE)
topic.words_social_w <- mallet.topic.words(topic.model_social_w, smoothed=TRUE, normalized=TRUE)
topic.labels_social_w <- mallet.topic.labels(topic.model_social_w, topic.words_social_w, 10)

lapply(1:nrow(topic.words_social_w), function(k) {
    top <- mallet.top.words(topic.model_social_w, topic.words_social_w[k,], 10) %>% select("term")
    cat(paste(k, top, "\n")) 
})
```

Visualization w
```{r}
m_social_w <- mallet_model(doc_topics = doc.topics_social_w, doc_ids = thesis.df_social_w$id, vocab = 
vocabulary_social_w, topic_words = topic.words_social_w, model = topic.model_social_w)
meta_social_w <- data.frame(id = thesis.df_social_w$id, pubdate = as.Date(thesis.df_social_w$Дата, "%d.%m.%Y"))
metadata(m_social_w) <- meta_social_w
series_social_w <- a(m_social_w, 'days')
theme_update(strip.text=element_text(size=7), 
axis.text=element_text(size=7))

a(m_social_w) %>%
plot_series(labels=topic_labels(m_social_w, 2))

```

